### ISSUE TITLE
Using paper-date-picker causes HTML import errors.

### ISSUE THREAD

**Issue by montyr75** [dam0vm3nt/custom_elements#2]
If I add `import 'package:custom_elements/paper_date_picker.dart';` to my project, Pub Serve has problems in the build:

`[Warning from ImportInliner on prediction_analytics|web/index.html]:
line 1, column 1 of lib\src\neon-animation\animations\fade-in-animation.html: Failed to inline HTML import: Could not find asset polymer_elements|lib/fade_in_animation_nodart.html.
null
<link rel="import" href="../../../../../packages/polymer_elements/fade_in_animation_nodart.html">
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Warning from ImportInliner on prediction_analytics|web/index.html]:
line 1, column 1 of lib\src\neon-animation\animations\fade-out-animation.html: Failed to inline HTML import: Could not find asset polymer_elements|lib/fade_out_animation_nodart.html.
null
<link rel="import" href="../../../../../packages/polymer_elements/fade_out_animation_nodart.html">
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by dam0vm3nt** [comment]
mmh, thank you monty. I'll check this out.

**Comment by dam0vm3nt** [comment]
was a "bug" in `custom element generator tool`. Fixed by hand, but need to propose a PR to jake to handle this cases ...
