### ISSUE TITLE
Angular2components

### ISSUE THREAD

**Issue by ghost** [dam0vm3nt/custom_elements#4]
I am also needing to ort some components.

For example a text editor like quiver.

Do you think I should match the dart teams own angular2dart components coding style.

Also I guess that some of the components in this report could start using their components as sib components ?

Just want your advice on this

**Comment by dam0vm3nt** [comment]
It all depends on witch web framework you are going to use for your project.

This package provides some JS `polymer` components to be used with `polymer-dart`.

If you going to use the `angular-dart` framework I definitively suggest you follow angular2dart coding style.

At the moment is not simple to make angular2dart play well with polymer components, so you have to choose one of the two.

I don't understand your last question but if you want some webcomponent to be added to this package just add an issue with references to it.

**Comment by ghost** [comment]
thanks for the answer. It really clears it up for me !! 

I will get busy with angular-dart. 
DO you happen to knwo where more components are that conform to the angular.dart pattern ?
I had a look on the dart pub at https://pub.dartlang.org/search?q=angular-dart&page=1
but there is very little.
Maybe its too early stll...

**Comment by dam0vm3nt** [comment]
You should take a look at this : https://github.com/dart-lang/angular2_components

**Comment by ghost** [comment]
ok ta
