### ISSUE TITLE
An error occurred loading file

### ISSUE THREAD

**Issue by Hecatoncheir** [dam0vm3nt/custom_elements#5]
When I run demo I get blank page in dartium and two errors in console:
![screenshot from 2016-11-21 10-41-46](https://cloud.githubusercontent.com/assets/910917/20474286/fe77887e-afd6-11e6-9067-f7917430e019.png)
And in terminal two warnings:
![screenshot from 2016-11-21 10-44-24](https://cloud.githubusercontent.com/assets/910917/20474398/50cc9c0e-afd7-11e6-8890-a547973b6880.png)

I would like to know whether I can use these components?

**Comment by dam0vm3nt** [comment]
Thanks, it is probably one missing mapping. I'll fix it asap.

**Comment by dam0vm3nt** [comment]
should be fixed here : https://github.com/dam0vm3nt/custom_elements/commit/cbfa89caa67e717d5fd506e1d0dcd40613d2c01f

**Comment by Hecatoncheir** [comment]
With version `0.0.12+1` in dartium console I get this error now:
![screenshot from 2016-11-28 10-48-35](https://cloud.githubusercontent.com/assets/910917/20660015/35833198-b558-11e6-8e86-b6d756e3ccf8.png)

**Comment by dam0vm3nt** [comment]
Updated the pubspec. The demo is using an unpublished version of polymer that supports a new strategy for dart-js mapping leveraging ES6.

**Comment by Hecatoncheir** [comment]
Now, work perfect. Thx!

**Comment by dam0vm3nt** [comment]
You're welcome. Thank for the feedback.
