### ISSUE TITLE
How to use the vaadin-grid in angular-dart ? 

### ISSUE THREAD

**Issue by abhishek-buragadda** [dam0vm3nt/custom_elements#8]
Can you please provide how to use the vaadin-grid in dart angular. I tried using it but with no success. If you provide a document that would be very useful.

**Comment by dam0vm3nt** [comment]
this project provides component for `polymer-dart`. I think you can follow the general instruction on using polymer elements with dart (look [here](https://dart.academy/dart-angular-2-and-polymer-together/) for instance).

Honestly I'm not using angular neither angular-dart so I can't tell you something better.
